package com.cn.java.data.model;

public class ZixunType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zixun_type.zixun_type_id
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	private Integer zixunTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zixun_type.zixun_type_name
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	private String zixunTypeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zixun_type.zixun_type_id
	 * @return  the value of zixun_type.zixun_type_id
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	public Integer getZixunTypeId() {
		return zixunTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zixun_type.zixun_type_id
	 * @param zixunTypeId  the value for zixun_type.zixun_type_id
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	public void setZixunTypeId(Integer zixunTypeId) {
		this.zixunTypeId = zixunTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zixun_type.zixun_type_name
	 * @return  the value of zixun_type.zixun_type_name
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	public String getZixunTypeName() {
		return zixunTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zixun_type.zixun_type_name
	 * @param zixunTypeName  the value for zixun_type.zixun_type_name
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	public void setZixunTypeName(String zixunTypeName) {
		this.zixunTypeName = zixunTypeName;
	}
}