package com.cn.java.data.dao;

import com.cn.java.data.model.ZixunType;
import com.cn.java.data.model.ZixunTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZixunTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int countByExample(ZixunTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int deleteByExample(ZixunTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int deleteByPrimaryKey(Integer zixunTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int insert(ZixunType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int insertSelective(ZixunType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	List<ZixunType> selectByExample(ZixunTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	ZixunType selectByPrimaryKey(Integer zixunTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ZixunType record, @Param("example") ZixunTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int updateByExample(@Param("record") ZixunType record, @Param("example") ZixunTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int updateByPrimaryKeySelective(ZixunType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zixun_type
	 * @mbggenerated  Sat Oct 15 15:41:44 CST 2016
	 */
	int updateByPrimaryKey(ZixunType record);
}